export default function Home() {
  return (
    <div style={{ padding: '2rem', fontFamily: 'Arial, sans-serif' }}>
      <h1>chipotle menu</h1>
      <p>This project was generated by AI Dreamer!</p>
      <div style={{ 
        background: '#f0f0f0', 
        padding: '1rem', 
        borderRadius: '8px',
        marginTop: '1rem'
      }}>
        <h2>Project Details</h2>
        <p><strong>Prompt:</strong> chipotle menu</p>
        <p><strong>Generated:</strong> 9/17/2025, 12:37:46 AM</p>
      </div>
    </div>
  );
}